apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: nextcloud
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: "v1.12.3" # Beispielversion, anpassen
    chart: cert-manager
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
