apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 465Gi # Anpassen an die Größe der SSD
  storageClassName: local-path-ssd
