apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-http01"
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
    - hosts:
        - team-s.duckdns.org
      secretName: nextcloud-tls-secret
  rules:
    - host: team-s.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud-service
                port:
                  number: 80
