apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:latest
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: nextcloud-postgresql
            - name: POSTGRES_DB
              value: nextcloud
            - name: POSTGRES_USER
              value: nextclouduser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgresql-secret
                  key: password
          volumeMounts:
            - name: nextcloud-storage
              mountPath: /var/www/html
            - name: nextcloud-configmap
              mountPath: /var/www/html/config/config.php
              subPath: config.php
              readOnly: true
      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc
        - name: nextcloud-configmap
          configMap:
            name: nextcloud-config
            items:
              - key: config.php
                path: config.php
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  config.php: |
    <?php
    $CONFIG = array (
      'trusted_domains' =>
      array (
        0 => 'localhost',
        1 => 'team-s.duckdns.org',
      ),
      'overwritehost' => 'team-s.duckdns.org',
      'overwriteprotocol' => 'https',
      'overwrite.cli.url' => 'https://team-s.duckdns.org',
    );
