apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-postgresql-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nextcloud-pvc-nfs
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-postgresql-secret
  namespace: nextcloud
type: Opaque
data:
  password: cGFzc3dvcmQxMjM=
